include:
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/License-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Container-Scanning.gitlab-ci.yml

stages:
- build
- test
- release

variables:
  CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE

workflow:
  rules:
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_COMMIT_BRANCH == "master"

.docker-job:
  image: docker:latest
  services:
  - docker:dind
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

docker-build:
  stage: build
  extends: .docker-job
  script:
  - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
  - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"

docker-release:
  stage: release
  extends: .docker-job
  script:
  - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE:latest"
  - docker push "$CI_REGISTRY_IMAGE:latest"
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
